/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-01-20 11:01:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.cal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cal.*;

public final class cal1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<HTML>\n");
      out.write("<HEAD><TITLE>\n");
      out.write("    Calendar: A JSP APPLICATION\n");
      out.write("</TITLE></HEAD>\n");
      out.write("\n");
      out.write("\n");
      out.write("<BODY BGCOLOR=\"white\">\n");
      out.write("\n");
      out.write("\n");
      cal.TableBean table = null;
      synchronized (session) {
        table = (cal.TableBean) _jspx_page_context.getAttribute("table", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (table == null){
          table = new cal.TableBean();
          _jspx_page_context.setAttribute("table", table, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      out.write('\n');

    table.processRequest(request);
    if (table.getProcessError() == false) {

      out.write("\n");
      out.write("\n");
      out.write("<!-- html table goes here -->\n");
      out.write("<CENTER>\n");
      out.write("<TABLE WIDTH=60% BGCOLOR=yellow CELLPADDING=15>\n");
      out.write("<TR>\n");
      out.write("<TD ALIGN=CENTER> <A HREF=cal1.jsp?date=prev> prev </A>\n");
      out.write("<TD ALIGN=CENTER> Calendar:");
      out.print( table.getDate() );
      out.write("</TD>\n");
      out.write("<TD ALIGN=CENTER> <A HREF=cal1.jsp?date=next> next </A>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("\n");
      out.write("<!-- the main table -->\n");
      out.write("<TABLE WIDTH=60% BGCOLOR=lightblue BORDER=1 CELLPADDING=10>\n");
      out.write("<TR>\n");
      out.write("<TH> Time </TH>\n");
      out.write("<TH> Appointment </TH>\n");
      out.write("</TR>\n");
      out.write("<FORM METHOD=POST ACTION=cal1.jsp>\n");

    for(int i=0; i<table.getEntries().getRows(); i++) {
       cal.Entry entr = table.getEntries().getEntry(i);

      out.write("\n");
      out.write("    <TR>\n");
      out.write("    <TD>\n");
      out.write("    <A HREF=cal2.jsp?time=");
      out.print( entr.getHour() );
      out.write(">\n");
      out.write("        ");
      out.print( entr.getHour() );
      out.write(" </A>\n");
      out.write("    </TD>\n");
      out.write("    <TD BGCOLOR=");
      out.print( entr.getColor() );
      out.write(">\n");
      out.write("    ");
 out.print(util.HTMLFilter.filter(entr.getDescription())); 
      out.write("\n");
      out.write("    </TD>\n");
      out.write("    </TR>\n");

    }

      out.write("\n");
      out.write("</FORM>\n");
      out.write("</TABLE>\n");
      out.write("<BR>\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("<TABLE WIDTH=60% BGCOLOR=yellow CELLPADDING=15>\n");
      out.write("<TR>\n");
      out.write("<TD ALIGN=CENTER>  ");
 out.print(util.HTMLFilter.filter(table.getName())); 
      out.write(" :\n");
      out.write("             ");
 out.print(util.HTMLFilter.filter(table.getEmail())); 
      out.write(" </TD>\n");
      out.write("</TR>\n");
      out.write("</TABLE>\n");
      out.write("</CENTER>\n");
      out.write("\n");

    } else {

      out.write("\n");
      out.write("<font size=5>\n");
      out.write("    You must enter your name and email address correctly.\n");
      out.write("</font>\n");

    }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</BODY>\n");
      out.write("</HTML>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
